apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # where kubernetes files are located 
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/client # dockerhub image for microservice
      context: client # name of the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js' #will look at react and update pods anythime we made changes inside this folder, if change happed oustide this folder scaffold will rebuild the image
            dest: .
    - image: stephengrider/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: stephengrider/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: stephengrider/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: stephengrider/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: stephengrider/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
